service: translation
workspaces:
  default:
    api_keys: [ public ]
    # Request parameters that form a routing key pattern.
    # e.g. [ src, tgt ] to route requests to workers based on the language direction
    routing_pattern: [ ]
    info: config/septilang.json
  smugri:
    api_keys: [ smugri ]
    routing_pattern: [ ]
    info: config/smugri.json